### ISSUE TITLE
Resize the sprite

### ISSUE THREAD

**Issue by MikaReesu** [tnantoka/sprite#1]
Hello,

First thank you for this package, it is easy to implement it.
Will it be possible to use the scale to decrease the size of the Sprite.

var scale = 0.5;

We will need a double for that.

Do you think you could update that? 

Also, would be for possible to flip the sprite?

Thank you

**Comment by tnantoka** [comment]
@MikaReesu 

Thanks for using my library.
Changed `scale` option to double type and added `flipX`, `flipY` options.

**Comment by MikaReesu** [comment]
Perfect! Thank you for the fast update. All is working fine!
